#+HUGO_BASE_DIR: ./
#+HUGO_SECTION: posts
#+HUGO_CODE_FENCE: nil

* Blog :blog:

*** Read Me
https://nethuml.github.io/posts/2022/06/blog-setup-with-hugo-org-mode/


** FSharp Blog :fsharp:dotnet:blog:
:PROPERTIES:
:EXPORT_FILE_NAME: fsharp-blog
:EXPORT_DATE: <2023-11-24 Fri 06:54>
:END:

I want to blog about F#, and .Net (or is it dotnet?)

#+begin_src fsharp :exports both
let greet () = "Hello, World!"

greet ()
#+end_src

#+RESULTS:
: Hello, World!


** Second Post :blog:
:PROPERTIES:
:EXPORT_FILE_NAME: second-post
:EXPORT_DATE: <2023-11-24 Fri 07:24>
:END:

This is the second post.
I want to try output instead f results.

#+begin_src fsharp :exports output
printfn "Hello, World!"
#+end_src

doesn't print output, but it does print results.


#+begin_src fsharp :session sp :exports code
let greet name = $"Hello, {name}!"
#+end_src

Which is called with

#+NAME: sp-call-greet
#+begin_src fsharp :session sp :exports both
greet "Jonathan P"
#+end_src

Which will then return:
#+RESULTS: sp-call-greet
: Hello, Jonathan!


** Advent of Code 2023 :advent:code:AoC:fsharp:
:PROPERTIES:
:EXPORT_FILE_NAME: 2023-advent-of-code
:EXPORT_DATE: <2023-11-24 Fri 07:39>
:END:

[[https://adventofcode.com/][Advent of Code]] will be starting soon, and I want to see if can manage any of the challenges using F#.


** AoC 2023, Day 1, Trebuchet :AoC:advent:cod:fsharp:
:PROPERTIES:
:EXPORT_FILE_NAME: aoc-2023-01
:EXPORT_DATE: <2023-12-01 Fri 08:06>
:END:

It is the first of December, and that means the start of [[https://adventofcode.com/2023][Advent of Code]].
I am going to make an attempt at this every day, posting my coding solutions (as much as possible in F#). I will not be posting the questions, as they can be found online, and I will not be posting my final answer.

[[https://adventofcode.com/2023/day/1][The first question is called /Trebuchet/]].

*** Part 1

I will first need a function that will be able to grab the first and last digits from a single row string.

#+begin_src fsharp :session aoc-2023-01 :exports both
let firstAndLastDigit (codedCalibration: string) =
    let digits =
        codedCalibration
        |> Seq.where (System.Char.IsDigit)
        |> Seq.toArray
    [| digits[0]; Seq.last digits |]
    |> System.String
    |> int

firstAndLastDigit "1abc2"
#+end_src

#+RESULTS:
: 12

This might be enough to put it all together.

#+begin_src fsharp :session aoc-2023-01 :exports code
let exampleInput =
    "1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet"

exampleInput.Split '\n'
|> Seq.map firstAndLastDigit
|> Seq.sum
#+end_src

This will have a final result of `142`.

*** Part 2

To complete part two, I want to first get a function that will extract all digits, and digit words out from a string.

#+begin_src fsharp :session aoc-2023-01 :exports code
let (|StartsWith|_|) (start: string) (full: string)  =
    if full.StartsWith(start) then Some full
    else None

let extract (input: string) =
    match input with
    | StartsWith "zero" _ -> Some 2
    | StartsWith "one" _ -> Some 1
    | StartsWith "two" _ -> Some 2
    | StartsWith "three" _ -> Some 3
    | StartsWith "four" _ -> Some 4
    | StartsWith "five" _ -> Some 5
    | StartsWith "six" _ -> Some 6
    | StartsWith "seven" _ -> Some 7
    | StartsWith "eight" _ -> Some 8
    | StartsWith "nine" _ -> Some 9
    | x when System.Char.IsDigit x[0] -> Some (int x[0..0])
    | _ -> None

let digitsOf (input: string) =
    seq { for i = 0 to input.Length - 1 do
          yield (extract input[i..]) }
    |> Seq.choose id
    |> Seq.toArray
#+end_src

With the input of this will return
#+NAME: aoc-2023-01-b-1
#+begin_src fsharp :session aoc-2023-01 :exports all :wrap example
digitsOf "two1nine"
#+end_src

This will return
#+RESULTS: aoc-2023-01-b-1
#+begin_example
| 2 | 1 | 9 |
#+end_example

And now I can update the original function to use this

#+begin_src fsharp :session aoc-2023-01 :exports both
let firstAndLastDigit (codedCalibration: string) =
    let digits = digitsOf codedCalibration
    [| digits[0]; Seq.last digits |]
    |> Array.map string
    |> (fun s -> System.String.Join ("", s))
    |> int

firstAndLastDigit "two1nine"
#+end_src

#+RESULTS:
: 29

And then I can test with the test input

#+begin_src fsharp :session aoc-2023-01 :exports code
let exampleInput =
    "two1nine
eightwothree
abcone2threexyz
xtwone3four
4nineeightseven2
zoneight234
7pqrstsixteen"

exampleInput.Split '\n'
|> Seq.map firstAndLastDigit
|> Seq.sum
#+end_src

This returns `281` which is the correct result for the test input.
#+RESULTS:
: 281
