baseURL = '/'
title = 'Jonathan Peel'
languageCode = 'en-za'
defaultcontentlanguage = "en"

theme = 'hello-friend'
paginate = 20

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = false

[params.logo]
  logoText = "Jonathan"
